version: "3.9"

services:
  trivia:
    build: .
    container_name: trivia-flask
    restart: unless-stopped

    ports:
      - "5002:8001"   # host:container

    environment:
      - FLASK_APP=src/trivia_web.py
      - TRIVIA_SECRET_KEY=change-this
      - TRIVIA_DB_PATH=/app/database/database.db

    volumes:
      - ./database:/app/database
      - ./src:/app/src       # optional, if you want live editing
      - ./src/templates:/app/templates
